### ISSUE TITLE
new bug found :)

### ISSUE THREAD

**Issue by zhang402115** [0xabu/pdfannots#63] opened 2022-11-14 16:53 UTC
Traceback (most recent call last):
  File "c:\users\yoga260\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\yoga260\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\yoga260\AppData\Local\Programs\Python\Python38\Scripts\pdfannots.exe\__main__.py", line 7, in <module>
  File "c:\users\yoga260\appdata\local\programs\python\python38\lib\site-packages\pdfannots\cli.py", line 141, in main
    doc = process_file(
  File "c:\users\yoga260\appdata\local\programs\python\python38\lib\site-packages\pdfannots\__init__.py", line 483, in process_file
    interpreter.process_page(pdfpage)
  File "c:\users\yoga260\appdata\local\programs\python\python38\lib\site-packages\pdfminer\pdfinterp.py", line 998, in process_page
    self.device.end_page(page)
  File "c:\users\yoga260\appdata\local\programs\python\python38\lib\site-packages\pdfminer\converter.py", line 81, in end_page
    self.receive_layout(self.cur_item)
  File "c:\users\yoga260\appdata\local\programs\python\python38\lib\site-packages\pdfannots\__init__.py", line 264, in receive_layout
    self.render(ltpage)
  File "c:\users\yoga260\appdata\local\programs\python\python38\lib\site-packages\pdfannots\__init__.py", line 364, in render
    self.render(child)
  File "c:\users\yoga260\appdata\local\programs\python\python38\lib\site-packages\pdfannots\__init__.py", line 364, in render
    self.render(child)
  File "c:\users\yoga260\appdata\local\programs\python\python38\lib\site-packages\pdfannots\__init__.py", line 359, in render
    self.update_pageseq(item)
  File "c:\users\yoga260\appdata\local\programs\python\python38\lib\site-packages\pdfannots\__init__.py", line 279, in update_pageseq
    x.update_pageseq(component, self.compseq)
  File "c:\users\yoga260\appdata\local\programs\python\python38\lib\site-packages\pdfannots\types.py", line 232, in update_pageseq
    self.pos.update_pageseq(component, pageseq)
  File "c:\users\yoga260\appdata\local\programs\python\python38\lib\site-packages\pdfannots\types.py", line 205, in update_pageseq
    if self.item_hit(component):
  File "c:\users\yoga260\appdata\local\programs\python\python38\lib\site-packages\pdfannots\types.py", line 197, in item_hit
    return (self.x >= item.x0  # type: ignore [no-any-return]
TypeError: '>=' not supported between instances of 'PSKeyword' and 'float'

**Comment by zhang402115** [comment] 2022-11-14 17:19
[20445911.2017.1310109.pdf](https://github.com/0xabu/pdfannots/files/10005437/20445911.2017.1310109.pdf)

**Comment by 0xabu** [comment] 2022-11-14 18:52
Hi, thanks for the report, but this looks like a duplicate of issue #54. I'm overdue for a new release (including the fix for that). Are you able to test with the latest version from github? Try `pip install git+https://github.com/0xabu/pdfannots.git`

**Comment by zhang402115** [comment] 2022-11-15 00:59
> Hi, thanks for the report, but this looks like a duplicate of issue #54. I'm overdue for a new release (including the fix for that). Are you able to test with the latest version from github? Try `pip install git+https://github.com/0xabu/pdfannots.git`

Dear colleague, thank you for your promt reply. I have tried with the command, pip install git+https://github.com/0xabu/pdfannots.git, though the problem still exists. Please see:

Traceback (most recent call last):
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in run_module_as_main
return run_code(code, main_globals, None,
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in run_code
exec(code, run_globals)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Scripts\pdfannots.exe_main.py", line 7, in
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pdfannots\cli.py", line 141, in main
doc = process_file(
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pdfannots_init.py", line 483, in process_file
interpreter.process_page(pdfpage)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pdfminer\pdfinterp.py", line 998, in process_page
self.device.end_page(page)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pdfminer\converter.py", line 81, in end_page
self.receive_layout(self.cur_item)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pdfannots_init.py", line 264, in receive_layout
self.render(ltpage)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pdfannots_init_.py", line 364, in render
self.render(child)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pdfannots_init_.py", line 364, in render
self.render(child)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pdfannots_init_.py", line 359, in render
self.update_pageseq(item)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pdfannots_init_.py", line 279, in update_pageseq
x.update_pageseq(component, self.compseq)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pdfannots\types.py", line 232, in update_pageseq
self.pos.update_pageseq(component, pageseq)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pdfannots\types.py", line 205, in update_pageseq
if self.item_hit(component):
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pdfannots\types.py", line 197, in item_hit
return (self.x >= item.x0 # type: ignore [no-any-return]
TypeError: '>=' not supported between instances of 'PSKeyword' and 'float'

Personally i am using this helpful program to collect the remarks i have made when reading articles. I have to do it one by one before i met this program. Now i am able to do it in a batch. I would much appreciate if a function could be added to process the files with address given in a certain txt file, or may trhe program be able to run in IDLE. For the momment, my solution is to draft the CMD command through IDLE, then copy it to CMD window to run.

As showned below:

import os,time # pdfannots 0.3
path =r'Z:\2022'
def get_filelist(dir):
Filelist = []
for home, dirs, files in os.walk(path):
for filename in files:
Filelist.append(os.path.join(home, filename))
Filelist.append( filename)
    return Filelist
a=get_filelist(path)
allFile=''
for i in a:
if i.endswith('.pdf'):
allFile=allFile+i+' '
if len(allFile)<8000:
continue
else:
anno='pdfannots '+allFile+'-o '+str(time.time())+'.md'
print(anno)
print('\n')
allFile=''
anno='pdfannots '+allFile+'-o '+str(time.time())+'.md'
print(anno)
print('\n')

**Comment by 0xabu** [comment] 2023-03-30 13:22
Sorry it took me so long to get to this report, and thanks for providing the sample PDF. I just tested on the latest version, and there is no crash, and one annotation is successfully retrieved, so I believe the issue is solved.

For batch processing, I would suggest a simple shell script, e.g.:
```
find mydir -name "*.pdf" -exec echo pdfannots {} -o {}.annots.md \;
```

**Closed as completed by 0xabu** 2023-03-30 13:22 UTC
Labels: bug, duplicate
